version: 2
jobs:
    build_project:
        working_directory: ~/angular-cli-templates
        docker:
            - image: circleci/node:12.9.1-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v2-dependencies-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: |
                    yarn install --frozen-lockfile
            - save_cache:
                name: Save Cache
                paths:
                    - ~/.cache
                    - node_modules
                key: v2-dependencies-{{ checksum "yarn.lock" }}
            - run:
                name: Prettier Check
                command: |
                    yarn prettier:check
            - run:
                name: Lint
                command: |
                    yarn lint
            - run:
                name: Unit Tests
                command: |
                    yarn test:ci
            - run:
                name: Build Project
                command: |
                    yarn build
    publish:
        docker:
            - image: circleci/node:12.9.1-browsers
        steps:
            - checkout
            - run:
                  name: Authenticate with registry
                  command: |
                      echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
                      echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            - run:
                  name: Publish @pxblue/angular-template-blank
                  command:  |
                      cd src/app/blank && yarn publish:package -b $CIRCLE_BRANCH
            - run:
                  name: Publish @pxblue/angular-template-routing
                  command:   |
                      cd src/app/routing && yarn publish:package -b $CIRCLE_BRANCH
            - run:
                  name: Publish @pxblue/angular-template-authentication
                  command:   |
                      cd src/app/auth-workflow && yarn publish:package -b $CIRCLE_BRANCH
workflows:
    version: 2
    angular-cli-templates:
        jobs:
            - build_project
            - publish:
                requires:
                    - build_project
                filters:
                    branches:
                        only:
                            - master
                            - dev
