version: 2
jobs:
    build_project:
        working_directory: ~/angular-cli-templates
        docker:
            - image: circleci/node:12.6-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v2-dependencies-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: |
                    yarn install --frozen-lockfile
            - save_cache:
                name: Save Cache
                paths:
                    - ~/.cache
                    - node_modules
                key: v2-dependencies-{{ checksum "yarn.lock" }}
            - run:
                name: Prettier Check
                command: |
                    yarn prettier:check
            - run:
                name: Lint
                command: |
                    yarn lint
            - run:
                name: Unit Tests
                command: |
                    yarn test:ci
            - run:
                name: Build Project
                command: |
                    yarn build

workflows:
    version: 2
    angular_design_patterns:
        jobs:
            - build_project
